export enum ArticleActionTypes {
  LOAD_ARTICLE_BY_ID = 'LOAD_ARTICLE_BY_ID',
  LOAD_ARTICLE_BY_ID_SUCCESS = 'LOAD_ARTICLE_BY_ID_SUCCESS',
  LOAD_ARTICLE_BY_ID_FAILED = 'LOAD_ARTICLE_BY_ID_FAILED',
}
